### ISSUE TITLE
Example in README does not compile

### ISSUE THREAD

**Issue by jgarte** [vitreo12/omni#154]
Hi Francesco,

I tried compiling the example in the README but I get the following error:

```
$ .nimble/bin/omni sine.omni
stack trace: (most recent call last)
omni_io.nim(651, 26)     omni_ins_inner
/home/jgart/.nimble/pkgs/omni_lang-0.4.0/omni_lang/core/lang/omni_io.nim(755, 12) template/generic instantiation of `omni_ins_inner` from here
/home/jgart/sine.omni(1, 7) Error: ins: Invalid syntax: '1'
```

This is what my sine.omni file contains:

```
ins:  1
outs: 1

init:
    phase = 0.0

sample:
    incr  = in1 / samplerate
    out1  = sin(phase * TWOPI)
    phase = (phase + incr) % 1.0
 ```
    
  This is the version of nim that I am using:

```
$ nim -v
Nim Compiler Version 1.4.6 [Linux: amd64]
Compiled at 2021-04-15
Copyright (c) 2006-2020 by Andreas Rumpf
```

Any ideas of how I can fix this? Should the README example be updated to reflect the current omni API or does the error lie elsewhere?

**Comment by vitreo12** [comment]
Hi!

What version of Omni are you using?

**Comment by vitreo12** [comment]
Ah, found the mistake... It's a regression from a rework I did a couple of releases ago. Will fix it ASAP! Thanks :)

**Comment by vitreo12** [comment]
I have rebased the 0.4.0 release to the new commit. If you `nimble uninstall omni` and `nimble install omni` again you should get it!

It definitely was a silly mistake on my end :)

**Comment by jgarte** [comment]
> Hi!
> 
> What version of Omni are you using?

```
 .nimble/bin/omni -v
Omni - version 0.4.0
(c) 2020-2021 Francesco Cameli
```

> If you nimble uninstall omni and nimble install omni again you should get it!

I uninstalled and installed it but not I get the error below:

```
$ .nimble/bin/omni Sine.omni

sh: nm: command not found
ERROR: Undefined 'perform' or 'sample' blocks.
```

Is there something wrong with my input file?

```
$ cat Sine.omni
ins:  1
outs: 1

init:
    phase = 0.0

sample:
    incr  = in1 / samplerate
    out1  = sin(phase * TWOPI)
    phase = (phase + incr) % 1.0
```

**Comment by vitreo12** [comment]
What Linux distribution are you using? It appears you don't have `nm` installed, which is a standard `gcc` utility.

**Comment by jgarte** [comment]
I'm on NixOS on this machine that is having the issues.

I think I have to do some homework on how to set up a proper environment on NixOS for doing work with nim/omni.  

Here are some issues regarding compiling packages with nim on NixOS in case you are interested:

https://discourse.nixos.org/t/unresolved-symbols-using-nim/11320/1
https://discourse.nixos.org/t/nix-flake-of-nim-lang-packages/5267
https://github.com/adamlwgriffiths/nix-nim

I tried on a 32 bit cpu that is running void linux and omni compiled the `Sine.omni` file just fine. 

I was able to inspect the `libSine.so` with `nm`.

**Comment by vitreo12** [comment]
I see! I have never used NixOS, but I am pretty sure the only problem in this case is to install `nm`. Glad it worked on a 32bit CPU, which I actually never tested Omni on :)

**Comment by jgarte** [comment]
I tried installing `nm` by installing the [binutils](https://search.nixos.org/packages?channel=20.09&show=binutils&from=0&size=50&sort=relevance&query=binutils) package which contains it .

```
whereis nm
nm: /nix/store/3xkamqvr4901xcwilzan3ijq29irpd8d-user-environment/bin/nm
```

```
 which nm
/home/jgart/.nix-profile/bin/nm
```
This is the error I get now when I try to compile `OmniSaw.omni`:

```
$ .nimble/bin/omni ~/.nimble/pkgs/omni-0.4.0/examples/OmniSaw.omni -o:./

/home/jgart/.nimble/pkgs/omni-0.4.0/examples/OmniSaw.omni(1, 1) template/generic instantiation of `params` from here
/home/jgart/.nimble/pkgs/omni_lang-0.4.0/omni_lang/core/lang/omni_io.nim(1872, 12) template/generic instantiation of `omni_params_inner` from here
/home/jgart/.nimble/pkgs/omni_lang-0.4.0/omni_lang/core/lang/omni_io.nim(1830, 41) Error: expression has no address
```

I get the same error for `Sine.omni`:

```
$ .nimble/bin/omni Sine.omni

/home/jgart/Sine.omni(1, 1) template/generic instantiation of `ins` from here
/home/jgart/.nimble/pkgs/omni_lang-0.4.0/omni_lang/core/lang/omni_io.nim(761, 12) template/generic instantiation of `omni_ins_inner` from here
/home/jgart/.nimble/pkgs/omni_lang-0.4.0/omni_lang/core/lang/omni_io.nim(719, 41) Error: expression has no address
```

**Comment by vitreo12** [comment]
Both examples compile for me... 

Do they work on your other machine? This might be a problem with NixOS.

**Comment by jgarte** [comment]
> Both examples compile for me...
> 
> Do they work on your other machine? This might be a problem with NixOS.

Yes, they both compile fine on the machine running void linux. I think this is a NixOS problem also.

I'll have to investigate what is the correct way to deal with this on NixOS. I'll ask in their [discourse](https://discourse.nixos.org/). Thanks!

**Comment by vitreo12** [comment]
I see! Let me know about your findings :)
