### ISSUE TITLE
Is it possible to use this library to generate very simple sounds

### ISSUE THREAD

**Issue by EasiestSoft** [vitreo12/omni#9]

**Comment by vitreo12** [comment]
What do you mean by simple sounds? Like short .wav files? This library does not do that. It is a DSL to specify audio objects to be exported in popular audio languages such as SuperCollider, Max or PD.

**Comment by EasiestSoft** [comment]
Thanks. yes, I mean generating short .wav files, similar to this C library:
https://www3.nd.edu/~dthain/courses/cse20211/fall2013/wavfile/

**Comment by vitreo12** [comment]
I am sorry, but this DSL won't do that. Its purpose is to define audio routines to be used in other audio programming environments.
